<?xml version="1.0" encoding="utf-8"?><Database Name="DB" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DB.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="IconEditor.Properties.Settings" SettingsPropertyName="DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Icon" Member="Icons">
    <Type Name="Icon">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Icon_IconPoint" Member="IconPoints" ThisKey="Id" OtherKey="IconId" Type="IconPoint" />
    </Type>
  </Table>
  <Table Name="dbo.IconPoint" Member="IconPoints">
    <Type Name="IconPoint">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="X" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Y" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IconId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Icon_IconPoint" Member="Icon" ThisKey="IconId" OtherKey="Id" Type="Icon" IsForeignKey="true" />
    </Type>
  </Table>
</Database>